# This is a basic workflow to help you get started with Actions

name: FIRST CI TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: message
        run: echo "checkout finish aws start"
        
      - name: aws 세팅
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 업로드
        run: aws deploy push --application-name deploy_first_app --description "deploy_first_app" --s3-location s3://uno-deploy/deploy/source.zip --source .

      - name: code deploy
        run: aws deploy create-deployment --application-name deploy_first_app --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name deploy_first_app_group --s3-location bucket=uno-deploy,bundleType=zip,key=deploy/source.zip

